GET http://localhost:3000/users

###
POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "hdck",
  "password": "hdck"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "name": "hdck",
  "password": "hdck"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "name": "hdck",
  "password": "wrong pass"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "name": "wrong usrname",
  "password": "hdck"
}